### ISSUE TITLE
Render Props API example missing?

### ISSUE THREAD

**Issue by Madgeniusblink** [react-spring/react-spring-examples#30] opened 2019-11-21 21:25 UTC
Hi,

I was wondering where I can find the example code of:
https://www.react-spring.io/docs/props/spring

**Comment by aleclarson** [comment] 2019-11-21 21:32
Duplicate of #28

Apparently the fix didn't get deployed. 😅 

The demos are here: https://github.com/react-spring/react-spring-examples/tree/renderprops/demos/renderprops

**Closed as completed** 2020-06-04 21:05 UTC
